# Generated by Django 2.1.4 on 2018-12-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0012_auto_20181208_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='private_key_path',
            field=models.FileField(blank=True, help_text='Path to the private key.', null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='csr',
            field=models.TextField(blank=True, null=True, verbose_name='CSR'),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='private_key_path',
            field=models.FileField(blank=True, help_text='Path to the private key.', null=True, upload_to='files'),
        ),
    ]
